# Generated by Django 4.0.4 on 2022-05-09 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='post',
            new_name='post1',
        ),
    ]
